image: sunoc/latex:latest

report:
  stage: build

  script:
    - apt-get update -y
    - apt-get install -y python3 python3-pip
    - pip install pygments
    - pdflatex --shell-escape README.tex
    - pdflatex --shell-escape README.tex

  artifacts:
    paths:
      - README.pdf
