image: sunoc/latex:latest

report:
  stage: build

  script:
    - apt-get update -y
    - apt-get install -y python3 python3-pip
    - pip install pygments
    - pdflatex --shell-escape README.tex
    - pdflatex --shell-escape README.tex
    - pdflatex --shell-escape install_ubuntu.tex
    - pdflatex --shell-escape install_ubuntu.tex
    - pdflatex --shell-escape vitis_ide.tex
    - pdflatex --shell-escape vitis_ide.tex

  artifacts:
    paths:
      - README.pdf
      - install_ubuntu.pdf
      - vitis_ide.pdf
