image: sunoc/latex:latest

main_report:
  stage: build
  script:
    - apt-get update -y
    - apt-get install -y python3 python3-pip
    - pip install pygments
    - pdflatex --shell-escape README.tex
    - pdflatex --shell-escape README.tex

  artifacts:
    paths:
      - README.pdf

ubuntu_report:
  stage: build
  script:
    - apt-get update -y
    - apt-get install -y python3 python3-pip
    - pip install pygments
    - pdflatex --shell-escape install_ubuntu.tex
    - pdflatex --shell-escape install_ubuntu.tex

  artifacts:
    paths:
      - install_ubuntu.pdf
